name: Build and test langtags.json
on:
  workflow_call:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2

    - name: Fetch and install the tooling
      run: |
        pip install \
          git+https://github.com/silnrsi/{sldrtools#sldrtools,palaso-python#palaso} \
          six \
          .

    - name: Find latest SLDR dependency
      uses: actions/github-script@v3
      id: find-sldr
      with:
        script: |
          const result = await github.actions
            .listArtifactsForRepo({
              owner: "silnrsi",
              repo: "sldr"
            })
          console.log(result.data.artifacts[0])
          return result.data.artifacts[0]
    - uses: actions/cache@v2
      id: cached-sldr
      with:
        path: |
          unflat
          flat
        key: sldr-${{fromJSON(steps.find-sldr.outputs.result).id}}
    - name: Download and extract SLDR dependency
      if: steps.cached-sldr.outputs.cache-hit != 'true'
      run: |
        wget --quiet --header "Authorization: token ${{secrets.GITHUB_TOKEN}}"  ${{fromJSON(steps.find-sldr.outputs.result).archive_download_url}} -O sldr.zip
        unzip -q sldr.zip
        rm sldr.zip
    
    # Build it
    - name: Generate langtags
      run: |
        make SLDR=unflat FLATDIR=flat build
    - uses: actions/upload-artifact@v2
      with:
        name: langtags
        path: |
          pub/**

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2

    - name: Fetch and install the tooling
      run: |
        pip install \
          git+https://github.com/silnrsi/{sldrtools#sldrtools,palaso-python#palaso} \
          six \
          .
    
    - uses: actions/download-artifact@v2
      with:
        name: langtags
        path: pub

    # Test it.
    - name: Test langtags
      id: langtags
      run: |
        make SLDR=unflat FLATDIR=flat test
        echo "::set-output name=need_commit::$(git diff -wU0 pub/langtags.json | grep '^+ ' | grep -v '\"date\":' | wc -l)"
#    - name: Commit built langtags
#      if: steps.langtags.output.need_commit != 0
#      uses: EndBug/add-and-commit@v5
#      with:
#        message: "GitHub Actions updated pub"
#        add: "pub/*"
#      env:
#        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
