name: Deploy to server
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string
    secrets:
      uploader_key:
        required: true
      server_address:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RSYNC_OPTS: -aP --no-p --no-g --no-t --compress --del -e "ssh -o StrictHostKeyChecking=no"
    steps:
    # Install our private key for uploading deliverable
    - uses: webfactory/ssh-agent@v0.5.0
      with:
        ssh-private-key: ${{ secrets.uploader_key }}
    # Download the artefact
    - uses: actions/download-artifact@v2
      with:
        name: langtags
    # Upload results
    - name: Upload langtags to /sites/s/data/${{ inputs.path }}
      run: echo rsync ${{env.RSYNC_OPTS}} langtags.{json,txt} ${{ secrets.server_address }}/sites/s/data/${{ inputs.path }}/
