name: Deploy to server
on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      RSYNC_OPTS: -aP --no-p --no-g --no-t --compress --del -e "ssh -o StrictHostKeyChecking=no"
    steps:
    # Install our private key for uploading deliverable
    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.UPLOADER_SSH_KEY }}
    # Download the artefact
    - uses: actions/download-artifact@v4
      with:
        name: langtags
    # Upload results
    - name: Upload langtags to /sites/s/data/${{ inputs.path }}
      run: rsync ${{ env.RSYNC_OPTS }} langtags.{json,txt} ${{ secrets.UPLOAD_TARGET }}/sites/s/data/${{ inputs.path }}/

  dispatch:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - name: Trigger findafont rebuild
      uses: peter-evans/repository-dispatch@v3
      with:
        token: ${{ secrets.REPO_DISPATCH_TOKEN }}
        repository: silnrsi/langfontfinder
        event-type: langtags-deployed
        client-payload: >- 
          {
            "release": "${{ github.ref_name == 'release' }}",
            "run_id": "${{ github.run_id }}"
          }
