name: Deploy langtags.json for staging

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [release]

jobs:
  deploy:
    needs: test
    uses: ./.github/workflows/deploy.yml
    with:
      path: .
    secrets:
      uploader_key: ${{ secrets.UPLOADER_SSH_KEY }}
      server_address: ${{ secrets.UPLOAD_TARGET }}