name: Build and deploy langtags for production

on:
  push:
    branches: [ release ]
    paths:
      - .github/workflows/**
      - bin/ltdb2alltags
      - bin/jsonlangtagstotxt
      - lib/**
      - source/**
      - tests/**
      - Makefile
      - setup.py
  pull_request:
    branches: [ release ]
    paths:
      - .github/workflows/**
      - bin/ltdb2alltags
      - bin/jsonlangtagstotxt
      - lib/**
      - source/**
      - tests/**
      - Makefile
      - setup.py
  workflow_dispatch:

jobs:
  build-langtags:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs: build-langtags
    uses: ./.github/workflows/deploy.yml
    with:
      path: .
    secrets:
      uploader_key: ${{ secrets.UPLOADER_SSH_KEY }}
      server_address: ${{ secrets.UPLOAD_TARGET }}