name: Deploy langtags.json for staging

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
    branches: [master]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - run: echo "${{toJSON(github.event.workflow_run)}}"

  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      path: staging
    secrets:
      uploader_key: ${{ secrets.UPLOADER_SSH_KEY }}
      server_address: ${{ secrets.UPLOAD_TARGET }}