name: Build and deploy langtags for staging

on:
  # push:
  #   branches: [ staging ]
  #   paths:
  #     - .github/workflows/**
  #     - bin/ltdb2alltags
  #     - bin/jsonlangtagstotxt
  #     - lib/**
  #     - source/**
  #     - tests/**
  #     - Makefile
  #     - setup.py
  # pull_request:
  #   branches: [ staging ]
  #   paths:
  #     - .github/workflows/**
  #     - bin/ltdb2alltags
  #     - bin/jsonlangtagstotxt
  #     - lib/**
  #     - source/**
  #     - tests/**
  #     - Makefile
  #     - setup.py
  workflow_dispatch:

jobs:
  build-langtags:
    uses: ./.github/workflows/build.yml
    secrets: inherit

  deploy:
    needs: call-build-langtags
    uses: ./.github/workflows/deploy.yml
    with:
      path: staging
    secrets:
      uploader_key: ${{ secrets.UPLOADER_SSH_KEY }}
      server_address: ${{ secrets.UPLOAD_TARGET }}