name: Build and deploy langtags.json for staging
on:
  push:
    branches: [master, feat/*, fix/*]
    paths:
      - .github/workflows/**
      - bin/ltdb2alltags
      - bin/jsonlangtagstotxt
      - lib/**
      - source/**
      - tests/**
      - Makefile
      - setup.py
  repository_dispatch:
    types: [sldr-deployed]
jobs:
  build:
    uses: ./.github/workflows/build.yml
    with:
      sldr-artifact-id: ${{ github.event.client_payload.artifact-id }}
      sldr-release: ${{ github.event.client_payload.release }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yml
    with:
      artifact-id: ${{ needs.build.outputs.artifact-id }}
      path: staging
    secrets:
      uploader_key: ${{ secrets.UPLOADER_SSH_KEY }}
      server_address: ${{ secrets.UPLOAD_TARGET }}
      repository_dispatch_pat: ${{ secrets.REPO_DISPATCH_TOKEN }}